title = 'Rocky Hutchins'
baseURL = ''

[menu]
    [[menu.hero]]
        name = 'Work With Me'
        title = 'Work With Me'
        URL = '/#work-with-me'
        weight = 100
    [[menu.hero]]
        name = 'Show Dates'
        title = 'Show Dates'
        URL = '/#upcoming-shows'

[params]
    primEmail = "info@example.com"
    primPhone = "(123) 456-7890"

[markup]
    [markup.goldmark]
        [markup.goldmark.parser]
            wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.renderer]
         unsafe = true
    [markup.highlight]
        style = "modus-vivendi"

[module]
    [[module.mounts]]
        source="static"
        target="static"
    [[module.mounts]]
        source="node_modules"
        target="static/node_modules"
    [[module.mounts]]
        source="favicon"
        target="static"

[build]
    writeStats = true
