title = 'Rocky Hutchins'
baseURL = 'https://rocky-hutchins.com'

[menu]
    [[menu.hero]]
        name = 'Work With Me'
        title = 'Work With Me'
        URL = '/#work-with-me'
        weight = 100
    [[menu.main]]
        name = 'Work With Me'
        title = 'Work With Me'
        URL = '/#work-with-me'
        weight = 100

[params]
    primEmail = "hockyrutchins@gmail.com"
    primPhone = "(517) 630-1783"
    firstName = "Rocky"
    lastName = "Hutchins"

[mediaTypes]
    [mediaTypes."text/vcf"]
    suffixes = ["vcf"]

[outputFormats.VCF]
mediaType = "text/vcf"
isPlainText = true
notAlternative = true

[markup]
    [markup.goldmark]
        [markup.goldmark.parser]
            wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.renderer]
         unsafe = true
    [markup.highlight]
        style = "modus-vivendi"

[module]
    [[module.mounts]]
        source="static"
        target="static"
    [[module.mounts]]
        source="node_modules"
        target="static/node_modules"
    [[module.mounts]]
        source="favicon"
        target="static"

[build]
    writeStats = true
